apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: helloworld-default
spec:
  destination:
    name: helloworld
  route:
  - labels:
      version: v1
    weight: 100
  - labels:
      version: v2
    weight: 0
